name: svg_to_flutter_path
description: Convert SVG Paths to Flutter Paths.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^5.6.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
